version: "3.9"

services:
  server:
    build: ./server/.
    command: python manage.py runserver 0.0.0.0:8000
    # network_mode: host
    env_file:
      - ./server/.env
    environment:
      - DATABASE_HOST=host.docker.internal
      
    ports:
      - 8000:8000
  redis:
    image: redis:7.2-alpine
  
  web:
    build: ./web/.
    command: node server.js
    # network_mode: host
    env_file:
      - ./web/.env
    environment:
     - HOSTNAME=0.0.0.0
     - NEXT_PUBLIC_DJ_API=server:8000
    ports:
    - 3000:3000
    depends_on:
      - server

  # nginx:
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - app-data:/usr/share/nginx/html/frontend
  #   depends_on:
  #     - server
  



